<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE assembly [
        <!ELEMENT assembly (formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes|outputFileNameMapping)*>
        <!ELEMENT outputFileNameMapping (#PCDATA)>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|destName|filtered)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        ]>
<assembly>

    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>wso2ei-${pom.version}</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/conf</directory>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/axis2/axis2.xml</exclude>
                <exclude>**/axis2/tenant-axis2.xml</exclude>
                <exclude>**/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**//tomcat/catalina-server.xml</exclude>
                <exclude>**//registry.xml</exclude>
                <exclude>**/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/tomcat/carbon/WEB-INF/web.xml</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/components</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>*dropins/**</exclude>
                <exclude>*patches/**</exclude>
                <exclude>*servicepacks/**</exclude>
                <exclude>*extensions/**</exclude>
                <exclude>*lib/**</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/dropins</directory>
            <outputDirectory>wso2ei-${pom.version}/dropins</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/lib</directory>
            <outputDirectory>wso2ei-${pom.version}/lib</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/patches</directory>
            <outputDirectory>wso2ei-${pom.version}/patches</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/servicepacks</directory>
            <outputDirectory>wso2ei-${pom.version}/servicepacks</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/extensions</directory>
            <outputDirectory>wso2ei-${pom.version}/extensions</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/bin</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/*.bat</exclude>
                <exclude>**/wrapper.conf</exclude>
                <exclude>build.xml</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

     <fileSet>
            <directory>src/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.bat</include>
                <include>build.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/bin</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/business-process/bin</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/*.bat</exclude>
                <exclude>build.xml</exclude>
            </excludes>
        </fileSet>


        <fileSet>
            <directory>./src/business-process/conf</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/business-process/bin</outputDirectory>
            <includes>
                <include>**.sh</include>
                <include>**.bat</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>src/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/lib</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository//plugins/saxon*.jar</exclude>
                <exclude>**/endorsed/xalan*.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>./src/resources/tomcat</directory>
            <outputDirectory>wso2ei-${pom.version}/conf/tomcat</outputDirectory>
            <includes>
                <include>**/catalina-server.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/resources</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/lib/endorsed</outputDirectory>
            <includes>
                <include>**/saxon9he.jar</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/resources/reports</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/resources/reports</outputDirectory>
            <includes>
                <include>**/*.jrxml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/conf</directory>
            <outputDirectory>wso2ei-${pom.version}/conf</outputDirectory>
            <includes>
                <include>**/sec.policy</include>
            </includes>
        </fileSet>
     <fileSet>
            <directory>../samples/product/services</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server/src</outputDirectory>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/resources</directory>
            <outputDirectory>wso2ei-${pom.version}/samples</outputDirectory>
            <includes>
                <include>**/*.pdf</include>
            </includes>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/java</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Client/src</outputDirectory>
            <excludes>
                <exclude>**/target</exclude>
                <exclude>**/target/**/*</exclude>
            </excludes>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Client</outputDirectory>
            <includes>
                <include>build.xml</include>
            </includes>
            <fileMode>644</fileMode>
            <directoryMode>775</directoryMode>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>wso2ei-samples.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/bin</outputDirectory>
            <includes>
                <include>wso2ei-samples.bat</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server</outputDirectory>
            <includes>
                <include>axis2server.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/scripts</directory>
            <outputDirectory>wso2ei-${pom.version}/samples/axis2Server</outputDirectory>
            <includes>
                <include>axis2server.bat</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../samples/product/src/main/conf/synapse</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/samples</outputDirectory>
            <fileMode>644</fileMode>
        </fileSet>

        <fileSet>
            <directory>../components/org.wso2.ei.styles/src/main/resources/web/styles/css</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/admin</outputDirectory>
            <includes>
                <include>**/**.css</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../components/org.wso2.ei.styles/src/main/resources/web/styles/images</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/images</outputDirectory>
            <includes>
                <include>**/**.gif</include>
                <include>**/**.png</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/conf/synapse-configs</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/server/synapse-configs
            </outputDirectory>
            <excludes>
                <exclude>**/empty.txt</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/conf/carbonapps</directory>
            <outputDirectory>wso2ei-${pom.version}/repository/deployment/server/carbonapps
            </outputDirectory>
            <excludes>
                <exclude>empty.txt</exclude>
            </excludes>
        </fileSet>

        <!--Multitenancy related file -->
        <fileSet>
            <directory>
                ../p2-profile/ei-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/multitenancy</outputDirectory>
            <includes>
                <include>**/stratos.xml</include>
                <include>**/multitenancy-packages.xml</include>
                <include>**/usage-throttling-agent-config.xml</include>
                <include>**/cloud-services-desc.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/multitenancy/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/conf/multitenancy
            </outputDirectory>
            <includes>
                <include>**/stratos.xml</include>
                <include>**/multitenancy-packages.xml</include>
                <include>**/usage-throttling-agent-config.xml</include>
                <include>**/cloud-services-desc.xml</include>
            </includes>
        </fileSet>


        <fileSet>
            <directory>
                ../p2-profile/ei-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf</outputDirectory>
            <includes>
                <include>**/tenant-mgt.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/business-process/conf
            </outputDirectory>
            <includes>
                <include>**/tenant-mgt.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/ei-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/identity
            </directory>
            <outputDirectory>wso2ei-${pom.version}/dbscripts/identity</outputDirectory>
            <includes>
                <include>**/**.sql</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>../styles/service/src/main/resources/web/styles/css</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/admin
            </outputDirectory>
            <includes>
                <include>**/**.css</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../styles/service/src/main/resources/web/styles/images</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/images
            </outputDirectory>
            <includes>
                <include>**/**.gif</include>
                <include>**/**.png</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>lib/home</directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/webapps/STRATOS_ROOT
            </outputDirectory>
        </fileSet>

        <!-- Adding Analytics related files to distribution -->

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/business-process</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/wso2</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/wso2/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>


        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/conf</directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/business-process/conf</outputDirectory>
            <excludes>
                <exclude>**/wso2</exclude>
                <exclude>**/*.sh</exclude>
                <exclude>**/axis2/axis2.xml</exclude>
                <exclude>**/axis2/tenant-axis2.xml</exclude>
                <exclude>**/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/repository/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**//tomcat/catalina-server.xml</exclude>
                <exclude>**//registry.xml</exclude>
                <exclude>**/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v2.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <!-- copying runtimes -->
        <fileSet>
            <directory>
                ../p2-profile/ei-profile/target/wso2carbon-core-${carbon.kernel.version}/lib/runtimes
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/lib/runtimes/
            </outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!--required by jaggery apps to be in CARBON_HOME-->
        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/modules
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/business-process/modules
            </outputDirectory>
            <includes>
                <include>**/*</include>
            </includes>
        </fileSet>

        <!--business-process db scripts-->

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/identity/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/identity</outputDirectory>
            <includes>
                <include>**/*.sql</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpel/create
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpel/create
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpel/drop
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpel/drop
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpel/truncate
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpel/truncate
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpmn/create
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpmn/create
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpmn/drop
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpmn/drop
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpmn/metadata
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpmn/metadata
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/bps/bpmn/upgrade
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/dbscripts/bps/bpmn/upgrade
            </outputDirectory>
        </fileSet>

        <!--  Copying BPS Jaggery Applications-->
        <fileSet>
            <directory>target/bpmn-explorer</directory>
            <outputDirectory>
                wso2ei-${pom.version}/wso2/business-process/repository/deployment/server/jaggeryapps/bpmn-explorer
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>target/humantask-explorer</directory>
            <outputDirectory>
                wso2ei-${pom.version}/wso2/business-process/repository/deployment/server/jaggeryapps/humantask-explorer
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>target/</directory>
            <outputDirectory>
                wso2ei-${pom.version}/wso2/business-process/repository/deployment/server/webapps
            </outputDirectory>
            <includes>
                <include>bpmn.war</include>
            </includes>
        </fileSet>
        <!--  End Copying BPS Jaggery Applications-->

        <fileSet>
            <directory>
                ../p2-profile/business-process-profile/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/security
            </directory>
            <outputDirectory>wso2ei-${pom.version}/wso2/business-process/conf/security
            </outputDirectory>
            <includes>
                <include>**/sso-sp-config.properties</include>
            </includes>
        </fileSet>
        <!-- BPS styles -->
        <fileSet>
            <directory>./src/business-process/styles/product/src/main/resources/web/styles/css
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/resources/allthemes/Default/admin
            </outputDirectory>
            <includes>
                <include>**/**.css</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>./src/business-process/styles/product/src/main/resources/web/styles/images
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/resources/allthemes/Default/images
            </outputDirectory>
            <includes>
                <include>**/**.gif</include>
                <include>**/**.png</include>
            </includes>
        </fileSet>
        <!--BPS Instance Clenup Scripts -->
        <fileSet>
            <directory>./src/business-process/cleanup-scripts</directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/wso2/business-process/repository/resources/cleanup-scripts
            </outputDirectory>
        </fileSet>

        <!-- BPS Process-tools related scripts/configs -->
        <fileSet>
            <directory>./src/business-process/process-tools/scripts</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/business-process/bin
            </outputDirectory>
            <includes>
                <include>processcleanuptool.sh</include>